# Default client configuration file for new MassOS upgrade utility.

# The online upgrade server to use.
# Only one server can be in use at a time.
# For details on server hosting, see the documentation for 'upgrade-massos'.
server: "https://archive.massos.org/builds/x86_64"

# The upgrade channel you wish to use.
# If not specified, it will use the server's default.
# But the server default can change at any time, so is recommended to specify.
# Note, however, that not all servers may use the same channel names.
# The official MassOS upgrade server uses 'stable' and 'experimental'.
channel: "experimental"

# Uncomment to override the server's checksum and/or signature policies.
# Note, however, that this is not recommended outside of for testing purposes.
#override-checksum-policy: "sloppy"
#override-signature-policy: "sloppy"
